### ISSUE TITLE
New Slicer logo rollout

### ISSUE THREAD

**Issue by jamesobutler** [Slicer/Slicer#5367]
The new Slicer logo was originally brainstormed and thoroughly discussed in https://discourse.slicer.org/t/proposed-new-slicer-logo/11295. The next step is the rollout to replace all the old Slicer logo usages.
![image](https://user-images.githubusercontent.com/15837524/103544638-6999fa80-4e6e-11eb-94c4-5c42cd2f63f8.png)

The new Slicer logo images files can be found at the google folder link on this post: https://discourse.slicer.org/t/proposed-new-slicer-logo/11295/97. 
I will also upload a zip file here in case that link expires for some reason: [SlicerNewLogo.zip](https://github.com/Slicer/Slicer/files/5762176/SlicerNewLogo.zip)

Primary Sites:
- [x] Slicer Desktop Icon and other uses in the source code: See ~~https://github.com/Slicer/Slicer/pull/5366~~ https://github.com/Slicer/Slicer/pull/5877
- [x] API Documentation: https://apidocs.slicer.org/master/index.html -- the icon is now updated, just the site is not updated (see #4906)
- [x] Organization Website: https://www.slicer.org/
  - [X] New website design: https://github.com/Slicer/slicer.org/tree/landing-page-redesign. 
![image](https://user-images.githubusercontent.com/15837524/103547055-e24e8600-4e71-11eb-8864-7aaf783b8750.png)
  - Old website design: https://github.com/Slicer/slicer.org/tree/slicer-org and https://github.com/mhalle/slicer4-download. if new website design hasn't rolled out yet
- [x] Slicer download subdomain (https://download.slicer.org/)
- [x] Discourse Forum Logo: https://discourse.slicer.org/
- [x] Discourse Forum Favicon: https://discourse.slicer.org/
- [x] ~~Slicer Wiki: https://www.slicer.org/wiki/Main_Page~~ -- we'll keep the old logo there, since there is/will be nothing for Slicer5
- [X] ReadTheDocs Logo: https://slicer.readthedocs.io/en/latest/
- [x] ~~ReadTheDocs Image resources https://github.com/Slicer/Slicer/releases/download/docs-resources/user_interface_main_window.png~~ -- the new logo will gradually replace the old one as new screenshots are created
- [x] ~~Slicer sticker design: as seen in this [post](https://discourse.slicer.org/t/feedback-on-slicer-sticker-design/6395)~~ -- designer of the new Slicer sticker will use the new logo
- [x] Slicer GitHub organization: https://github.com/Slicer

Social:
- [x] Wikipedia: https://en.wikipedia.org/wiki/3DSlicer => tracked in https://github.com/Slicer/Slicer/issues/6072
- [x] Twitter: https://twitter.com/3dslicerapp
- [x] Facebook: https://www.facebook.com/pages/3DSlicer/103767359661291 => tracked in https://github.com/Slicer/Slicer/issues/6071
- [x] YouTube: https://www.youtube.com/c/3DSlicerChannel / https://www.youtube.com/channel/UC11x1iQ7ydSIFYw4L6wveXg

Third Party:
- [x] Midas Server: http://slicer.kitware.com/ -- no action needed, the server was shut down
- [x] New extension server: https://slicer-packages.kitware.com/
- [x] Kitware's Platform page: https://www.kitware.com/platforms/#3d-slicer

Slicer Extensions using the logo or elements of old logo:
- [X] SlicerAstro: https://github.com/Punzo/SlicerAstro/blob/master/SlicerAstroIcon.png
- [x] ArduinoController: https://github.com/pzaffino/SlicerArduinoController/blob/master/ArduinoController.png See: https://github.com/pzaffino/SlicerArduinoController/pull/2
- [x] Matlab Bridge: https://github.com/PerkLab/SlicerMatlabBridge/blob/master/MatlabBridge.png See: https://github.com/PerkLab/SlicerMatlabBridge/pull/7
- [x] PETDICOMExtension: https://github.com/QIICR/Slicer-PETDICOMExtension/blob/master/PETDICOMExtension.png See: https://github.com/QIICR/Slicer-PETDICOMExtension/pull/19
- [x] SlicerOpenCV: https://github.com/Slicer/SlicerOpenCV/blob/master/SlicerOpenCV.png See: https://github.com/Slicer/SlicerOpenCV/pull/66
- [x] SlicerIGSIO: https://github.com/IGSIO/SlicerIGSIO/blob/master/SlicerIGSIO.png See: https://github.com/IGSIO/SlicerIGSIO/pull/10
- [x] SlicerToKiwiExporter: https://github.com/jcfr/SlicerToKiwiExporter/blob/master/SlicerToKiwiExporterLogo.png See: https://github.com/jcfr/SlicerToKiwiExporter/pull/8
- [x] TCIABrowser: https://github.com/QIICR/TCIABrowser/blob/master/TCIABrowser.png -- creme color Slicer logo currently used. See: https://github.com/QIICR/TCIABrowser/pull/45
- [x] ~~SlicerProstate: https://github.com/SlicerProstate/SlicerProstate/blob/master/SlicerProstate.png~~ -- the maintainer will update the logo if significant update is released
- [x] ~~mpReview: https://github.com/SlicerProstate/mpReview/blob/master/Resources/Icons/mpReview.png~~ -- the maintainer will update the logo if significant update is released
- [x] ~~SlicerITKUltrasound: https://github.com/KitwareMedical/SlicerITKUltrasound/blob/master/SlicerITKUltrasound.png -- still using ITK's old logo --creme color Slicer logo currently used.~~ -- the maintainer will update the logo if significant update is released

**Comment by jamesobutler** [comment]
@lassoan Do you manage https://twitter.com/3dslicerapp? If so, could you update the profile picture? Currently, it is an old style logo (see below)
![image](https://user-images.githubusercontent.com/15837524/118416492-f4d99700-b67d-11eb-95fb-74dc27268798.png)

Links to the new logo files are available in the original post.

Same goes for updating the Slicer Discourse Logo and the Slicer Discourse Favicon, if you have the admin rights to update those items.

**Comment by lassoan** [comment]
I have access to Slicer Forum branding. The 4 images attached below are used currently. @jamesobutler could you update them with the new logo?

![3DSlicerLogo-app-icon-centered-512](https://user-images.githubusercontent.com/307929/118910122-ff03cb80-b8f1-11eb-9597-fe6bc355c8c2.png)
![3DSlicerLogo-HorizontalF-large2 png](https://user-images.githubusercontent.com/307929/118910123-ff03cb80-b8f1-11eb-89c0-4fb6ad63b084.png)
![apple_touch_icon](https://user-images.githubusercontent.com/307929/118910125-ff03cb80-b8f1-11eb-888c-f1dd280ae098.png)
![Slicer-discourse-64x64](https://user-images.githubusercontent.com/307929/118910126-ff9c6200-b8f1-11eb-8276-a41be0fa5ad3.png)

**Comment by jamesobutler** [comment]
I believe we have all 4 in the linked set of files: Mark, Mark with Horizontal Text, Touch icon (I believe is just a 180x180 version), and discourse icon

I do not have access to change such branding directly on the forum as I only have member access.

**Comment by lassoan** [comment]
I've updated the icons on Discourse.

**Comment by lassoan** [comment]
@jcfr could you update the logo in the [Github Slicer organization](https://github.com/Slicer)? I've checked and I don't have access to that.

**Comment by lassoan** [comment]
I've tried to update the [Slicer logo on Wikipedia](https://en.wikipedia.org/wiki/File:3DSlicerLogo.png#file) but I could not figure out how to do/request upload of a new file revision.

**Comment by lassoan** [comment]
@jcfr could you update the logo in the [Github Slicer organization](https://github.com/Slicer)? I've checked and I don't have access to that.

I think all the other usages of the logo are either very low priority or very complicated to change. So, if we update the logo in the Github Slicer organization then we can close this issue for 4.13 (and can create new issues for updating the icon on wikipedia and facebook).

**Comment by pieper** [comment]
> @jcfr could you update the logo in the [Github Slicer organization](https://github.com/Slicer)? I've checked and I don't have access to that.

I was able to update it.

**Comment by lassoan** [comment]
Thank you! I've added separate tickets for tracking icon updates on Wikipedia and Facebook and the rest of the updates are low priority (the icon will eventually be updated as side effects of updates), so we can close this issue now.
